# .github/workflows/app-deploy.yml
name: Build & deploy app

on:
  push:
    branches: [ main ]
    paths:
      - "static/**"
      - "templates/**"
      - "app.py"
      - "Dockerfile"
      - ".github/workflows/app-deploy.yml"

env:
  REGISTRY_NAME:   jwendtacr
  REGISTRY_LOGIN:  jwendtacr.azurecr.io
  IMAGE_BASE_NAME: flaskweb
  WEBAPP_NAME:     jwendt-web
  RESOURCE_GROUP:  BCSAI2024-DEVOPS-STUDENTS-A-UAT

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # ─────────────  CHECKOUT & LOGIN  ───────────────────────────
    - uses: actions/checkout@v4

    - name: Azure login (service-principal)
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # ─────────────  GET ACR ADMIN CREDS  ────────────────────────
    - name: Fetch ACR admin credentials
      id: acr-creds
      run: |
        CREDS=$(az acr credential show \
          --name $REGISTRY_NAME \
          --resource-group $RESOURCE_GROUP \
          --query "{u:username,p:passwords[0].value}" -o tsv)
        echo "ACR_USER=$(echo $CREDS | awk '{print \$1}')" >> $GITHUB_ENV
        echo "ACR_PASS=$(echo $CREDS | awk '{print \$2}')" >> $GITHUB_ENV

    # ─────────────  DOCKER LOGIN / BUILD / PUSH  ────────────────
    - name: Docker login to ACR
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.REGISTRY_LOGIN }}
        username:     ${{ env.ACR_USER }}
        password:     ${{ env.ACR_PASS }}

    - name: Generate image tag
      run: echo "VER=${{ github.ref_name }}-$(date +'%Y.%m.%d.%H%M')" >> $GITHUB_ENV

    - name: Build & push image
      run: |
        docker build . \
          -t $REGISTRY_LOGIN/$IMAGE_BASE_NAME:$VER \
          -t $REGISTRY_LOGIN/$IMAGE_BASE_NAME:latest
        docker push $REGISTRY_LOGIN/$IMAGE_BASE_NAME:$VER
        docker push $REGISTRY_LOGIN/$IMAGE_BASE_NAME:latest

    # ─────────────  DEPLOY TO WEB APP  ──────────────────────────
    - name: Deploy container to Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name:     ${{ env.WEBAPP_NAME }}
        registry-url: ${{ env.REGISTRY_LOGIN }}
        username:     ${{ env.ACR_USER }}
        password:     ${{ env.ACR_PASS }}
        images:       ${{ env.REGISTRY_LOGIN }}/${{ env.IMAGE_BASE_NAME }}:${{ env.VER }}
