# .github/workflows/app-deploy.yml
name: Build & deploy app

on:
  push:
    branches: [ main ]
    paths:
      - "static/**"
      - "templates/**"
      - "app.py"
      - "Dockerfile"
      - ".github/workflows/app-deploy.yml"

env:
  REGISTRY_LOGIN:  jwendtacr.azurecr.io       # <─ ACR login-server
  IMAGE_BASE_NAME: flaskweb                   # the repo inside ACR
  WEBAPP_NAME:     jwendt-web
  RESOURCE_GROUP:  BCSAI2024-DEVOPS-STUDENTS-A-UAT

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # ── Azure CLI sign-in with the service principal secret ─────────
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # ── Log in to ACR **with the AAD token** ────────────────────────
    - name: Docker login to ACR
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.REGISTRY_LOGIN }}
        # NOTE: no username / password inputs here

    # ── Build & push image ──────────────────────────────────────────
    - name: Generate image tag
      run: echo "VER=${{ github.ref_name }}-$(date +'%Y.%m.%d.%H%M')" >> $GITHUB_ENV

    - name: Build & push image
      run: |
        docker build . \
          -t $REGISTRY_LOGIN/$IMAGE_BASE_NAME:$VER \
          -t $REGISTRY_LOGIN/$IMAGE_BASE_NAME:latest
        docker push $REGISTRY_LOGIN/$IMAGE_BASE_NAME:$VER
        docker push $REGISTRY_LOGIN/$IMAGE_BASE_NAME:latest

    # ── Deploy container to the Web App ─────────────────────────────
    - name: Deploy to App Service
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.WEBAPP_NAME }}
        images:   ${{ env.REGISTRY_LOGIN }}/${{ env.IMAGE_BASE_NAME }}:$VER

    # ── Post-deployment actions ─────────────────────────────────────