name: Build & deploy app

on:
  push:
    branches: [ main ]
    paths:
      - "Dockerfile"
      - "app.py"
      - "static/**"
      - "templates/**"
      - ".github/workflows/deploy-app.yml"

env:
  REGISTRY_NAME:   jwendtacr                 # <─ added for clarity
  REGISTRY_LOGIN:  jwendtacr.azurecr.io
  IMAGE_BASE_NAME: flaskweb
  WEBAPP_NAME:     jwendt-web
  RESOURCE_GROUP:  BCSAI2024-DEVOPS-STUDENTS-A-UAT

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    # checkout repo
    - uses: actions/checkout@v4

    # Azure login with the service-principal stored in secret AZURE_CREDENTIALS
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # ───────────── login to ACR (uses the token from az login) ─────────────
    - name: ACR login (CLI token)
      run: az acr login --name ${{ env.REGISTRY_NAME }}

    # generate an image tag like 347fcb0-20240602-1315
    - name: Generate image tag
      run: echo "VER=${GITHUB_SHA::7}-$(date +'%Y%m%d%H%M')" >> $GITHUB_ENV

    # build & push
    - name: Build & push image
      run: |
        docker build . \
          -t $REGISTRY_LOGIN/$IMAGE_BASE_NAME:$VER \
          -t $REGISTRY_LOGIN/$IMAGE_BASE_NAME:latest
        docker push $REGISTRY_LOGIN/$IMAGE_BASE_NAME:$VER
        docker push $REGISTRY_LOGIN/$IMAGE_BASE_NAME:latest

    # deploy
    - name: Deploy to App Service
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.WEBAPP_NAME }}
        images:   ${{ env.REGISTRY_LOGIN }}/${{ env.IMAGE_BASE_NAME }}:latest
